language: python
python:
- 3.4

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python3-numpy python3-scipy

install:
- pip3 install pytest nose
- pip3 install -e .

script:
- pytest
