language: python
python:
  - "3.4"
  - "3.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-numpy
  - sudo apt-get install -y python3-dev 
  - sudo apt-get install -y python3-pip
  - sudo apt-get install -y python3-wheel

# command to install dependencies
install: 
  - "pip install tensorflow"
  - "pip install -e ."

# command to run tests
script: python -m unittest

# safelist
branches:
  only:
  - master
  - dev
